# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: employee.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'employee.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65mployee.proto\x12\x08\x65mployee\"B\n\x0f\x45mployeeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x12\n\ndepartment\x18\x03 \x01(\t\"T\n\x15UpdateEmployeeRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\ndepartment\x18\x04 \x01(\t\"\x18\n\nEmployeeId\x12\n\n\x02id\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty\"O\n\x10\x45mployeeResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\ndepartment\x18\x04 \x01(\t\"=\n\x0c\x45mployeeList\x12-\n\temployees\x18\x01 \x03(\x0b\x32\x1a.employee.EmployeeResponse\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe8\x02\n\x0f\x45mployeeService\x12G\n\x0e\x43reateEmployee\x12\x19.employee.EmployeeRequest\x1a\x1a.employee.EmployeeResponse\x12?\n\x0bGetEmployee\x12\x14.employee.EmployeeId\x1a\x1a.employee.EmployeeResponse\x12:\n\x0fGetAllEmployees\x12\x0f.employee.Empty\x1a\x16.employee.EmployeeList\x12M\n\x0eUpdateEmployee\x12\x1f.employee.UpdateEmployeeRequest\x1a\x1a.employee.EmployeeResponse\x12@\n\x0e\x44\x65leteEmployee\x12\x14.employee.EmployeeId\x1a\x18.employee.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'employee_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPLOYEEREQUEST']._serialized_start=28
  _globals['_EMPLOYEEREQUEST']._serialized_end=94
  _globals['_UPDATEEMPLOYEEREQUEST']._serialized_start=96
  _globals['_UPDATEEMPLOYEEREQUEST']._serialized_end=180
  _globals['_EMPLOYEEID']._serialized_start=182
  _globals['_EMPLOYEEID']._serialized_end=206
  _globals['_EMPTY']._serialized_start=208
  _globals['_EMPTY']._serialized_end=215
  _globals['_EMPLOYEERESPONSE']._serialized_start=217
  _globals['_EMPLOYEERESPONSE']._serialized_end=296
  _globals['_EMPLOYEELIST']._serialized_start=298
  _globals['_EMPLOYEELIST']._serialized_end=359
  _globals['_DELETERESPONSE']._serialized_start=361
  _globals['_DELETERESPONSE']._serialized_end=394
  _globals['_EMPLOYEESERVICE']._serialized_start=397
  _globals['_EMPLOYEESERVICE']._serialized_end=757
# @@protoc_insertion_point(module_scope)
