# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import employee_pb2 as employee__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in employee_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmployeeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEmployee = channel.unary_unary(
                '/employee.EmployeeService/CreateEmployee',
                request_serializer=employee__pb2.EmployeeRequest.SerializeToString,
                response_deserializer=employee__pb2.EmployeeResponse.FromString,
                _registered_method=True)
        self.GetEmployee = channel.unary_unary(
                '/employee.EmployeeService/GetEmployee',
                request_serializer=employee__pb2.EmployeeId.SerializeToString,
                response_deserializer=employee__pb2.EmployeeResponse.FromString,
                _registered_method=True)
        self.GetAllEmployees = channel.unary_unary(
                '/employee.EmployeeService/GetAllEmployees',
                request_serializer=employee__pb2.Empty.SerializeToString,
                response_deserializer=employee__pb2.EmployeeList.FromString,
                _registered_method=True)
        self.UpdateEmployee = channel.unary_unary(
                '/employee.EmployeeService/UpdateEmployee',
                request_serializer=employee__pb2.UpdateEmployeeRequest.SerializeToString,
                response_deserializer=employee__pb2.EmployeeResponse.FromString,
                _registered_method=True)
        self.DeleteEmployee = channel.unary_unary(
                '/employee.EmployeeService/DeleteEmployee',
                request_serializer=employee__pb2.EmployeeId.SerializeToString,
                response_deserializer=employee__pb2.DeleteResponse.FromString,
                _registered_method=True)


class EmployeeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllEmployees(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEmployee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmployeeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEmployee,
                    request_deserializer=employee__pb2.EmployeeRequest.FromString,
                    response_serializer=employee__pb2.EmployeeResponse.SerializeToString,
            ),
            'GetEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmployee,
                    request_deserializer=employee__pb2.EmployeeId.FromString,
                    response_serializer=employee__pb2.EmployeeResponse.SerializeToString,
            ),
            'GetAllEmployees': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllEmployees,
                    request_deserializer=employee__pb2.Empty.FromString,
                    response_serializer=employee__pb2.EmployeeList.SerializeToString,
            ),
            'UpdateEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEmployee,
                    request_deserializer=employee__pb2.UpdateEmployeeRequest.FromString,
                    response_serializer=employee__pb2.EmployeeResponse.SerializeToString,
            ),
            'DeleteEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEmployee,
                    request_deserializer=employee__pb2.EmployeeId.FromString,
                    response_serializer=employee__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'employee.EmployeeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('employee.EmployeeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmployeeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee.EmployeeService/CreateEmployee',
            employee__pb2.EmployeeRequest.SerializeToString,
            employee__pb2.EmployeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee.EmployeeService/GetEmployee',
            employee__pb2.EmployeeId.SerializeToString,
            employee__pb2.EmployeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllEmployees(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee.EmployeeService/GetAllEmployees',
            employee__pb2.Empty.SerializeToString,
            employee__pb2.EmployeeList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee.EmployeeService/UpdateEmployee',
            employee__pb2.UpdateEmployeeRequest.SerializeToString,
            employee__pb2.EmployeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/employee.EmployeeService/DeleteEmployee',
            employee__pb2.EmployeeId.SerializeToString,
            employee__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
